### ISSUE TITLE
Close drawer if any of the items is clicked?

### ISSUE THREAD

**Issue by 511234** [cantek-nextdoor/frontend#6]
![20231023_shouldclose](https://github.com/cantek-nextdoor/frontend/assets/76647602/03b0b8cf-3257-43e9-b9a1-642a6010dc73)

Personally I want the drawer on the left to be closed if I navigate to a new page, so I don't have to do it myself.
How do you think?
@TomYYHong @yukfaihsu @JordanLDavid

**Comment by JordanLDavid** [comment]
I don't mind leaving it open. I checked other sites like youtube or even google classroom and they leave it open when navigating.  Maybe you can close it when you click outside the navigation panel. 

If you close it everytime you change page, it makes it harder to navigate between pages due to extra button clicks.
